[Doing] Fix #1171
ppoffice/hexo-theme-icarus pull request #1178
Opened 2023-01-30 10:39 UTC by flc1125

2023-01-30 10:55 UTC, flc1125 commented
@ppoffice Help!! What is this?

```bash
Cannot find schema definition /misc/copyright.json.
```

2023-01-30 15:26 UTC, ppoffice commented on include/schema/common/footer.json
> +            "$ref": "/misc/copyright.json",
You do not need to include `/misc/copyright.json` here since the schema is defined in place rather than in another file.

2023-01-30 15:27 UTC, ppoffice commented on .gitignore
> +package-lock.json
This change is irrelevant to this PR. Please remove.

2023-01-31 03:17 UTC, ppoffice requested changes

2023-01-31 03:17 UTC, ppoffice commented on include/schema/common/footer.json
> -            "description": "Copyright text",
No, don't remove the schema. We still need this section to verify user's configuration file. What I mean is just removing `"$ref": "/misc/copyright.json"`

2023-01-31 15:20 UTC, merged

2023-02-01 01:00 UTC, flc1125 commented
@ppoffice How soon is the next release expected?

2023-02-01 01:59 UTC, ppoffice commented
No ETA right now. But you can npm install the git repo directly if it is want you want.

2023-02-01 06:51 UTC, flc1125 commented
> No ETA right now. But you can npm install the git repo directly if it is want you want.

OK, I'll wait for the next version.